# Generated by Django 5.2.5 on 2025-10-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_alter_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
    ]
